const countryMap = {
    "Default": 10,
    "Algeria": 30,
    "Australia": 10,
    "Bangladesh": 37,
    "Brazil": 10,
    "Cambodia": 49,
    "Canada": 25,
    "China": 34,
    "European Union": 20,
    "Guyana": 38,
    "India": 27,
    "Indonesia": 32,
    "Iraq": 39,
    "Israel": 17,
    "Japan": 24,
    "Malaysia": 24,
    "Mexico": 20,
    "New Zealand": 10,
    "Nicaragua": 19,
    "Nigeria": 14,
    "Norway": 16,
    "Pakistan": 30,
    "Philippines": 18,
    "South Africa": 31,
    "South Korea": 26,
    "Sri Lanka": 44,
    "Switzerland": 32,
    "Taiwan": 32,
    "Thailand": 37,
    "United Kingdom": 10,
    "United States": 0,
    "Venezuela": 15,
    "Vietnam": 46
};