const countryMap = {
    "Default": 10,
    "Algeria": 10,
    "Australia": 10,
    "Bangladesh": 10,
    "Brazil": 10,
    "Cambodia": 10,
    "Canada": 10,
    "China": 145,
    "European Union": 10,
    "Guyana": 10,
    "India": 10,
    "Indonesia": 10,
    "Iraq": 10,
    "Israel": 10,
    "Japan": 10,
    "Malaysia": 10,
    "Mexico": 10,
    "New Zealand": 10,
    "Nicaragua": 10,
    "Nigeria": 10,
    "Norway": 10,
    "Pakistan": 10,
    "Philippines": 10,
    "South Africa": 10,
    "South Korea": 10,
    "Sri Lanka": 10,
    "Switzerland": 10,
    "Taiwan": 10,
    "Thailand": 10,
    "United Kingdom": 10,
    "United States": 0,
    "Venezuela": 10,
    "Vietnam": 10
};